/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Story */
        Story: {
            /** Title */
            title: string;
            /**
             * Description
             * @default null
             */
            description: string | null;
            /** Date Mode */
            date_mode: string;
        };
        /** CalendarMetadata */
        CalendarMetadata: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Source
             * @enum {string}
             */
            source: "builtin" | "plugin";
            /**
             * Extra Props
             * @default null
             */
            extra_props: {
                [key: string]: unknown;
            } | null;
        };
        /** Phase */
        Phase: {
            /** Base Time */
            base_time: number[];
            /**
             * Ref Time
             * @default null
             */
            ref_time: number[] | components["schemas"]["Phase"] | null;
        };
        /** Moai */
        Moai: {
            /** Name */
            name: string;
            /** @default null */
            base_time: components["schemas"]["Phase"] | null;
            /** Description */
            description: string;
            /** Materials */
            materials?: string[];
            /**
             * Extra Props
             * @default null
             */
            extra_props: {
                [key: string]: unknown;
            } | null;
            /** Journal */
            journal?: {
                [key: string]: [
                    string,
                    string | null
                ];
            };
            /** Base Time Display */
            readonly base_time_display: string | null;
        };
        /** Drift */
        Drift: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            start_time: components["schemas"]["Phase"];
            /** @default null */
            end_time: components["schemas"]["Phase"] | null;
            /**
             * Description
             * @default null
             */
            description: string | null;
            /**
             * Moais
             * @default null
             */
            moais: string[] | null;
            /** Flat Start */
            readonly flat_start: number[];
            /** Flat End */
            readonly flat_end: number[] | null;
            /** Start Tick */
            readonly start_tick: number;
            /** End Tick */
            readonly end_tick: number | null;
            /** Start Time Display */
            readonly start_time_display: string;
            /** End Time Display */
            readonly end_time_display: string | null;
        };
        /**
         * Narrative
         * @description A chapter outline selecting drift groups or individual events.
         */
        Narrative: {
            /** Subject */
            subject: string[];
            /** Observer */
            observer: string;
            /** Drifts */
            drifts: components["schemas"]["Drift"][];
        };
        /** GraphLink */
        GraphLink: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Label */
            label: string;
            /** Relations */
            relations: string;
            /** Bidirectional */
            bidirectional: boolean;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** LinkGraph */
        LinkGraph: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Links */
            links: components["schemas"]["GraphLink"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
